version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: todo-postgres
    environment:
      POSTGRES_DB: Todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    ports:
      - "6996:5432"

  todo-app:
    build: .
    container_name: todo-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Todo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000
    ports:
      - "8080:8080"
